# Player column position constants
PLAYER_COLUMN_X_START = 28
PLAYER_COLUMN_X_END = 308
PLAYER_ROW_HEIGHT = 80
PLAYER_IMAGE_X_START = 28
PLAYER_IMAGE_X_END = 108
PLAYER_NAME_X_START = 120
PLAYER_NAME_Y_START = 14
NAME_HEIGHT = 24
PLAYER_INFO_X_START = 120
PLAYER_INFO_Y_START = 39
PLAYER_INFO_HEIGHT = 20
PLAYER_INFO_X_END = 178
ROWS_START_Y = 96
